2023-10-07 23:29:06,009 - DEBUG - This is the first level
2023-10-07 23:29:06,009 - INFO - This is the second level
2023-10-07 23:29:06,009 - WARNING - third level
2023-10-07 23:29:06,010 - ERROR - Fourth level
2023-10-07 23:29:06,010 - CRITICAL - fifth level
2023-10-07 23:29:06,010 - ERROR - The error occured
Traceback (most recent call last):
  File "F:\Waheed\WOrk\logging\loggingtut.py", line 20, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2023-10-07 23:29:06,030 - INFO - test the custom logger.
